# Generated by Django 3.2.16 on 2023-01-25 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ones', models.SmallIntegerField(null=True)),
                ('twos', models.SmallIntegerField(null=True)),
                ('threes', models.SmallIntegerField(null=True)),
                ('fours', models.SmallIntegerField(null=True)),
                ('fives', models.SmallIntegerField(null=True)),
                ('sixes', models.SmallIntegerField(null=True)),
                ('three_kind', models.SmallIntegerField(null=True)),
                ('four_kind', models.SmallIntegerField(null=True)),
                ('full_house', models.SmallIntegerField(null=True)),
                ('short_straight', models.SmallIntegerField(null=True)),
                ('long_straight', models.SmallIntegerField(null=True)),
                ('yahtzee', models.SmallIntegerField(null=True)),
                ('chance', models.SmallIntegerField(null=True)),
                ('top_score', models.SmallIntegerField(null=True)),
                ('bonus', models.SmallIntegerField(null=True)),
                ('top_total', models.SmallIntegerField(null=True)),
                ('bottom_total', models.SmallIntegerField(null=True)),
                ('grand_total', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL)),
                ('scores1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1scores', to='yahtzee.scores')),
                ('scores2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2scores', to='yahtzee.scores')),
            ],
        ),
    ]
