# Generated by Django 3.2.16 on 2023-01-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahtzee', '0003_alter_game_active_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turns_remaining',
            field=models.IntegerField(default=26),
        ),
    ]
