# Generated by Django 3.2.16 on 2023-01-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahtzee', '0004_game_turns_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='active_player',
            field=models.CharField(default='player1', max_length=10),
        ),
    ]
