# Generated by Django 3.2.5 on 2021-10-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_dividend'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='currency_con',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='currency_con',
            field=models.FloatField(default=1),
        ),
    ]
