# Generated by Django 3.2.5 on 2021-10-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20211016_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='currency',
            field=models.CharField(default='EUR', max_length=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='EUR', max_length=5),
        ),
    ]
