# Generated by Django 3.2.3 on 2021-06-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
