# Generated by Django 3.2.5 on 2021-10-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20211016_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='currency',
            field=models.CharField(default='EUR', max_length=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='EUR', max_length=15),
        ),
    ]
