# Generated by Django 3.2.3 on 2021-06-18 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210610_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
