# Generated by Django 2.2.5 on 2021-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('url', models.URLField(blank=True)),
                ('view', models.CharField(blank=True, max_length=50)),
                ('button_text', models.CharField(blank=True, max_length=30)),
                ('button_view', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
