# Generated by Django 3.2.3 on 2021-06-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='view',
            field=models.CharField(default='portfolio', max_length=50),
            preserve_default=False,
        ),
    ]
