# Generated by Django 3.2.3 on 2021-06-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='button_text',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='button_view',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
