# Generated by Django 3.2.3 on 2021-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210621_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='view',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
