# Generated by Django 2.2.5 on 2021-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.FloatField(default=2015)),
                ('day', models.FloatField(default=1)),
                ('part', models.FloatField(default=1)),
                ('memo', models.TextField(blank=True)),
            ],
        ),
    ]
