# Generated by Django 3.2.5 on 2021-07-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advent', '0002_auto_20210623_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
