# Generated by Django 3.2.5 on 2021-07-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advent', '0004_remove_advent_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='advent',
            name='part',
            field=models.IntegerField(default=1),
        ),
    ]
