# Generated by Django 3.2.5 on 2021-07-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advent', '0007_advent_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advent',
            name='github',
        ),
    ]
