# Generated by Django 3.2.5 on 2021-11-07 19:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worttester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wort', models.CharField(max_length=50)),
                ('memo', models.TextField(blank=True)),
                ('art', models.CharField(choices=[('nomen', 'Nomen'), ('pronomen', 'Pronomen'), ('verb', 'Verb'), ('adjectiv', 'Adjectiv'), ('adverb', 'Adverb'), ('praeposition', 'Präposition'), ('konjunktion', 'Konjunktion'), ('zwischenruf', 'Zwischenruf')], default='nomen', max_length=12)),
                ('artikel', models.CharField(blank=True, max_length=3)),
                ('englisch', models.CharField(max_length=50)),
                ('quelle', models.CharField(max_length=50)),
                ('referenz', models.TextField(blank=True)),
                ('wurzel1', models.CharField(max_length=50)),
                ('wurzel2', models.CharField(max_length=50)),
                ('wurzel3', models.CharField(max_length=50)),
                ('wurzel4', models.CharField(max_length=50)),
                ('wurzel5', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
