# Generated by Django 3.2.5 on 2021-11-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worttester', '0002_rename_worttester_wort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wort',
            name='wurzel1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='wort',
            name='wurzel2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='wort',
            name='wurzel3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='wort',
            name='wurzel4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='wort',
            name='wurzel5',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
